ci:
  skip:
    - poetry-lock

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "3.2.2"
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        stages:
          - commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude_types:
          - binary
      - id: mixed-line-ending
        exclude_types:
          - binary
      - id: trailing-whitespace
        exclude_types:
          - binary
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.23.0"
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
